### ISSUE TITLE
With 'Remove transient options' checked going to check other red options pop-up the transient message

### ISSUE THREAD

**Issue by garrett-eclipse** [DavidAnderson684/WP-Optimize#100]
Hello,

Minor issue here. When you go to optimize and check off the Red items they pop-up an alert associated with their specific option. When you have the 'Remove transient options' checkbox checked and go to check another option like 'Clean post meta data' then the pop-up will still pertain to the transient options and not the clean post meta. If you don't touch/check the 'Remove transient options' then checking 'clean post meta' produces the appropriate message. So it's only when you have first interacted with the transient option that others don't pop-up the correct message.

See screen, in it I've checked the transient option (got first pop-up, and closed) then check I click 'Clean post meta data' I get the same transient pop-up a second time;
![screen shot 2016-10-31 at 8 42 01 am](https://cloud.githubusercontent.com/assets/8726005/19861141/afabe01c-9f48-11e6-88a8-3b6c3b370cfd.png)

Let me know if you need any further information.

Thanks

**Comment by ruhanirabin** [comment]
Thanks for reporting this :) i guess this is a problem with the JS prompt. I will take a look inside @garrett-eclipse

**Comment by DavidAnderson684** [comment]
This issue has been verified to not exist in current releases of the plugin - closing.

**Comment by garrett-eclipse** [comment]
Thanks @DavidAnderson684 I'll second that.
