### ISSUE TITLE
revisions count can't count over 999

### ISSUE THREAD

**Issue by ruhanirabin** [DavidAnderson684/WP-Optimize#101]
Reported by Tomasz 
—
I've been using your fabulous outstanding plugin for just a five minutes and I think that I have already found a tiny bug in version 1.9.1.

I have a blog network and on ten of my blogs everything was OK.

When I visited 11-th one, the biggest on, to my extreme surprise your plugin reported that it is about to remove 1 (one!) post revision.

With 486 posts edited for past 2 years that is rather hard to believe.

After processing cleanup process it turned out that my DB size was reduced by 20 MB!

So, it seems that if there are more than 999 revisions to be removed, your plugin displays 1 instead of 1XXX.

**Comment by DavidAnderson684** [comment]
This issue has been copied to our internal tracker - closing.
