### ISSUE TITLE
admin.php?page=WP-Optimize error

### ISSUE THREAD

**Issue by viperguynaz** [DavidAnderson684/WP-Optimize#52]
when going to plugin homepage (1.8.9.7) on WP (4.0.1), I keep getting: "The page cannot be displayed because an internal server error has occurred." - I can get to the tables & info pages of the plugin though.

**Comment by DavidAnderson684** [comment]
Hi,

We're having a clean-up of historical issues here. This issue is from several releases ago now; please can you open a fresh thread at https://wordpress.org/support/plugin/wp-optimize/ if you find that the issue still exists?

Many thanks,
David
