### ISSUE TITLE
Current database size not updating

### ISSUE THREAD

**Issue by en7jos** [DavidAnderson684/WP-Optimize#53]
Very minor issue and perhaps you are already aware:

The 'current database size' info does not update after optimizing until the page is reloaded.  The 'you can save xMb' changes to 'you have saved xMb', but the current database size stays the same.  Reloading the page updates it to the new value.

Keep up the good work please!
Cheers, James

**Comment by ruhanirabin** [comment]
Hi There en7jos, your database format might not be compatible. Also you might have one or more corrupted tables. I will check the code but I can’t replicate this problem. Try using phpMyAdmin to repair or check your table consistency. 

:)

-- RR
On February 10, 2015 at 6:53:51 AM, en7jos (notifications@github.com) wrote:

Very minor issue and perhaps you are already aware:

The 'current database size' info does not update after optimizing until the page is reloaded. The 'you can save xMb' changes to 'you have saved xMb', but the current database size stays the same. Reloading the page updates it to the new value.

Keep up the good work please!
Cheers, James

**Comment by DavidAnderson684** [comment]
This issue is believed to no longer exist in the current release and its AJAXification; closing. (Please re-open at http://wordpress.org/support/plugin/wp-optimize/ if you find otherwise).
