### ISSUE TITLE
New Feature: Clearing oEmbed Cache

### ISSUE THREAD

**Issue by ramiy** [DavidAnderson684/WP-Optimize#55]
I develop lots of projects that use oEmbed. It would be nice if WP-Optimize will allow me to clear oembed cache stored in the WP database.

It's not hard to implement this, you just need the search in **wp_postmeta** table all the fields starting with **_oembed_** and delete them. Just like you delete transians and draft's.

For more info, i found this post on the web:
https://siteorigin.com/clearing-oembed-cache/

Rami Y.
GenerateWP.com

**Comment by ramiy** [comment]
I use this SQL to clear my embed cache:
```
DELETE
FROM   'wp_postmeta' 
WHERE  'meta_key' 
LIKE   '%_oembed_%'
```

Rami Y.
GenerateWP.com

**Comment by ruhanirabin** [comment]
I will test it out. Thanks :)

**Comment by DavidAnderson684** [comment]
This issue is now being tracked in our internal tracking tool - closing the old Github issue.
