### ISSUE TITLE
Postmeta not removed, when post was in trash

### ISSUE THREAD

**Issue by hurik** [DavidAnderson684/WP-Optimize#56]
When a post is in trash and I gets removed while optimizing, the postmeta doesn't get removed.

**Comment by fastlinemedia** [comment]
We ran into a similar issue and it appears to be with revisions. If a post has revisions that have post meta, and the post is in the trash, the revision's post meta will not be deleted by WP-Optimize leaving it orphaned. 

This issue can cause a database to have thousands of orphaned rows. Any chance we can get some eyes on this? 

Thanks!

**Comment by hurik** [comment]
No update in over a year ... I moved to this plugin: https://de.wordpress.org/plugins/wp-sweep/

This one removes everything without orphaned Post Meta and also can remove orphaned Post Meta.
