### ISSUE TITLE
Prevent timeouts in admin/php

### ISSUE THREAD

**Issue by shawnlunny** [DavidAnderson684/WP-Optimize#61]
This plugin reaches a 1 minute timeout on our hosting provider (WPEngine). Is there a way to use ajax or something so the tool doesn't time out?

Thanks!

**Comment by ruhanirabin** [comment]
at this moment i dont have enough time to refactor it. I will look into it as soon as possible :) thanks @shawnlunny. Keeping this open!

**Comment by DavidAnderson684** [comment]
Hi Shawn,

New versions of the plugin have had a big refactor, and now do optimizations over AJAX in more piece-meal fashion. This might solve your issue. If not, please can you open a fresh issue at http://wordpress.org/support/plugin/wp-optimize/ and let us know?

Many thanks,
David
