### ISSUE TITLE
Full multisite support

### ISSUE THREAD

**Issue by mennobouma** [DavidAnderson684/WP-Optimize#65]
Hi Ruhani,

Does this plugin gets full multisite support? I mean with global network settings and network optimizing instead of per site? I'm running a big multisite and it's impossible for me to optimize each site one-by-one.

Thanks. Menno

**Comment by joransrb** [comment]
I wonder this also...

**Comment by pmsteil** [comment]
Also need this, thanks.

**Comment by petebarr** [comment]
+1

**Comment by DavidAnderson684** [comment]
Duplicate of https://github.com/DavidAnderson684/WP-Optimize/issues/32 - closing.
