### ISSUE TITLE
Notices are not displayed

### ISSUE THREAD

**Issue by Kerfred** [DavidAnderson684/WP-Optimize#83]
Hello,

Since I installed your plugin, the PHP notices are not displayed anymore.
It's annoying to not see the notices during plugin development.
Did you deactivate them in the plugin? If yes, could you reactivate them?
Thanks.

**Comment by ruhanirabin** [comment]
You should deactivate my plugin first. It's not designed for use with debugging systems.

**Comment by Kerfred** [comment]
Thank you but this is not an acceptable answer.
I like your plugin very much and I use it on several sites. I think it is
better than other similar plugins.

I am also a plugins developer, and I need to display the warnings and
notices that may trigger with my plugins. You should do it too.
A WordPress plugin shouldn't have to hide the warnings and notices.

Have a good weekend.

Best regards,
Kerfred
--

2016-01-16 8:23 GMT+01:00 Ruhani Rabin <notifications@github.com>:

> You should deactivate my plugin first. It's not designed for use with
> debugging systems.
>
>

**Comment by ruhanirabin** [comment]
You can try the develop branch. It should be fixed that issue. It wasn't release to the WP repository.

**Comment by Kerfred** [comment]
Great. Thank you.

**Comment by DavidAnderson684** [comment]
This issue is believed to not exist in recent releases. Thanks for the report; please let us know (in the wordpress.org support forum) if you find this problem again.
