### ISSUE TITLE
remove the german translation

### ISSUE THREAD

**Issue by kniebremser** [DavidAnderson684/WP-Optimize#91]
Hi!
you can remove the german translation from the core. The translation is to 100% translated in translate.wordpress.org. The translation is also about already maintained.

**Comment by ruhanirabin** [comment]
@kniebremser what do i need to do .. just remove the language files here ? i should keep the directory i think

**Comment by kniebremser** [comment]
The best solution of all is: the directory maintained only with the .pot file.
The existing .po and .mo files can be deleted. The already translated strings were completely taken in translate.wordpress.org.

**Comment by DavidAnderson684** [comment]
This has been done in recent releases. Closing.
